config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#top'
  
  resources :users
  resources :posts
  resources :microposts
  post 'favs/:id' => 'favs#create', as: :fav
  delete 'favs/:id' => 'favs#destroy', as: :unfav
  
  get 'login' => 'sessions#new'
  
  post 'login' => 'sessions#create'
  
  get 'logout' => 'sessions#destroy'
  
  post 'responses/:id' => 'responses#create', as: :responses
  
  
  

end

app/models/fav.rb
class Fav < ActiveRecord::Base
  belongs_to :user
  belongs_to :micropost
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  has_many :favs, dependent: :destroy
  has_many :fav_users, through: :favs, source: :user
  has_many :responses, dependent: :destroy
  has_many :response_users, through: :responses, source: :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
end

app/models/response.rb
class Response < ActiveRecord::Base
  has_many :microposts
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts
  has_many :favs, dependent: :destroy
  has_many :fav_microposts, through: :favs, source: :micropost
  has_many :responses, dependent: :destroy
  has_many :response_microposts, through: :responses, source: :micropost
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello
    render text: 'hello app'
  end
end

app/controllers/favs_controller.rb
class FavsController < ApplicationController
  
  def create
    user = User.find_by(id: session[:user_id])
    micropost = Micropost.find(params[:id])
    fav = user.favs.build(micropost_id: micropost.id)
    fav.save
    redirect_to micropost
  end
  
  def destroy
    user = User.find_by(id: session[:user_id])
    fav = user.favs.find_by(micropost_id: params[:id])
    fav.destroy
    micropost = Micropost.find(params[:id])
    redirect_to micropost
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def create
    user = User.find_by(id: session[:user_id])
    micropost = user.microposts.build(micropost_params)
    micropost.save
    redirect_to root_path
  end
  
  def show
    @micropost = Micropost.find(params[:id])
    @user_favs = @micropost.favs
    @response = Response.new
    @responses = @micropost.responses
  end
  
  
  private
    def micropost_params
      params.require(:micropost).permit(:title, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
      @posts = Post.all
      @post = Post.new
    end
    
    def show
      @post = Post.find(params[:id])
    end
    
    def new
      @post = Post.new
    end
    
    
    
    def create
      @current_user = User.find_by(id: session[:user_id])
      @post = @current_user.posts.build(post_params)
      @post.save
      redirect_to root_path
    end

    
    def update
      post = Post.find(params[:id])
      post.update_attributes(post_params)
      redirect_to root_path
    end
    
    def edit
      @post = Post.find(params[:id])
    end
    
    def destroy
      post = Post.find(params[:id])
      post.destroy
      redirect_to root_path
    end
    
    private
      def post_params
        params.require(:post).permit(:title, :content)
      end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def create
    user = User.find_by(id: session[:user_id])
    response = user.responses.build(micropost_id: params[:id])
    response.content = params[:response][:content]
    response.save
    micropost = Micropost.find_by(id: params[:id])
    redirect_to micropost
  end
  
  private
   def response_params
     params.require(:response).permit(:content)
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    session[:user_id] = user.id
    redirect_to root_path
  end
  
  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
    @user = User.find_by(id: session[:user_id])
    @micropost = Micropost.new
    @microposts = Micropost.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    @user.save
    redirect_to root_path
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    redirect_to root_path
  end
  
  
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :profile)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favs_helper.rb
module FavsHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/microposts/show.html.erb
<h1><%= @micropost.title %></h1>

<p><%= @micropost.content %></p>

<% if User.find_by(id: session[:user_id]).fav_microposts.include?(@micropost) %>
  <%= link_to '☆を消す', unfav_path, method: :delete %>
<% else %>
  <%= link_to '☆', fav_path, method: :post %> x <%= @micropost.favs.count %>
<% end %>

<h2>この投稿へのコメント一覧</h2>
<ul>
  <% @responses.each do |response| %>
  <li><%= response.content %> by <% user = User.find_by(id: response.user_id) %><%= link_to user.name, user %></li>
  <% end %>
</ul>

<h2>コメントを残す</h2>
<%= form_for(@response) do |f| %>
<%= f.text_area :content %>
<p><%= f.submit '送信' %></p>
<% end %>

app/views/posts/edit.html.erb
<h1>投稿の編集</h1>
<%= form_for(@post) do |f| %>

<p>タイトル</p>
<%= f.text_field :title %>

<p>内容</p>
<%= f.text_area :content %>

<p><%= f.submit '更新' %></p>

<% end %>

app/views/posts/index.html.erb
<h1>みんなの投稿</h1>

<%= link_to '新規投稿', new_post_path %>

<h2>投稿一覧</h2>
<ul>
  <% @posts.each do |post| %>
  <li><%= post.title %> | <%= post.content %></li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>新しい投稿</h1>
<%= form_for(@post) do |f| %>
  <p>タイトル</p>
  <%= f.text_field :title %>
  
  <p>内容</p>
  <%= f.text_area :content %>
  
  <p><%= f.submit '投稿' %></p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<%= link_to '編集', edit_post_path %> | <%= link_to '削除', post_path, method: :delete %>

app/views/static_pages/top.html.erb
<% if session[:user_id]  %>
<h1><%= @user.name %>さんようこそ！</h1>
<p>これは練習用のアプリです。</p>

<%= link_to 'マイページ', @user %> | <%= link_to 'ユーザー一覧', users_path %> | <%= link_to 'ログアウト', logout_path %>

<h2>新規投稿</h2>
<%= form_for(@micropost) do |f| %>
<p>タイトル</p>
<%= f.text_field :title %>
<p>内容</p>
<%= f.text_area :content %>
<p><%= f.submit '投稿' %></p>
<% end %>

<h2>投稿一覧</h2>
<ul>
  <% @microposts.each do |micropost| %>
  <li><%= link_to micropost.title, micropost %> by <%= link_to micropost.user.name, micropost.user %> | ☆ x <%= micropost.favs.count %></li>
  <% end %>
</ul>

<% else %>

<h1>土台アプリ</h1>
<p>これは練習用のアプリです。</p>

<%= link_to 'ログイン', login_path %> | <%= link_to '新規登録', new_user_path %>


<% end %>

app/views/users/edit.html.erb
<h1>ユーザーの更新</h1>

<%= form_for(@user) do |f| %>

<p>名前</p>
<%= f.text_field :name %>

<p>メールアドレス</p>
<%= f.email_field :email %>

<p>プロフィール</p>
<%= f.text_area :profile %>

<p>
<%= f.submit '作成' %>
</p>


<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<ul>
    <% @users.each do |user| %>
    <li><%= link_to user.name, user %> | <%= user.profile %></li>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>新しいユーザーの作成</h1>

<%= form_for(@user) do |f| %>

<p>名前</p>
<%= f.text_field :name %>

<p>メールアドレス</p>
<%= f.email_field :email %>

<p>プロフィール</p>
<%= f.text_area :profile %>

<p>
<%= f.submit '作成' %>
</p>


<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>さんのマイページ</h1>
<p>メールアドレス | <%= @user.email %></p>
<p>プロフィール | <%= @user.profile %></p>
<%= link_to '編集', edit_user_path %> | <%= link_to '削除', user_path, method: :delete %>

<h2><%= @user.name %>さんの投稿一覧</h2>
<ul>
  <% @microposts.each do |micropost| %>
  <li><%= link_to micropost.title, micropost %></li>
  <% end %>
</ul>